namespace Inova.Application.DTOs.Session;

public class SessionResponseDto
{
    public int Id { get; set; }  // ← Generated by DB
    public int ConsultantId { get; set; }  // ← Customer chooses
    public DateTime ScheduledDate { get; set; }  // ← Customer chooses
    public TimeSpan ScheduledTime { get; set; }  // ← Customer chooses
    public decimal DurationHours { get; set; }  // ← Customer chooses
    public decimal TotalAmount { get; set; }  // ← Calculated!
    public string Status { get; set; }  // ← Set to "Pending"
    public DateTime CreatedAt { get; set; }  // ← Set by code
}